# Generated by Django 6.1.1 on 2026-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição/Produto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor R$')),
                ('data', models.DateField(verbose_name='Data')),
                ('cartao', models.CharField(choices=[('adriana', 'Adriana'), ('cassio', 'Cássio')], max_length=10, verbose_name='Cartão')),
            ],
        ),
    ]
